steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-images/hf-elim-pubsub
      - -f
      - services/hf_elim_pubsub/Dockerfile
      - .
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-images/hf-elim-pubsub
